[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-23-09.raw"
led1 = [ 652, 383, 5,]
led2 = [ 658, 377, 5,]
led3 = [ 611, 385, 5,]
led4 = [ 617, 379, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-23-23.raw"
led1 = [ 91, 466, 5,]
led2 = [ 93, 459, 5,]
led3 = [ 67, 472, 5,]
led4 = [ 69, 465, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-23-38.raw"
led1 = [ 1090, 376, 5,]
led2 = [ 1095, 368, 5,]
led3 = [ 1055, 372, 5,]
led4 = [ 1061, 366, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-23-55.raw"
led1 = [ 664, 47, 5,]
led2 = [ 671, 41, 5,]
led3 = [ 621, 47, 5,]
led4 = [ 627, 42, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-24-16.raw"
led1 = [ 677, 653, 5,]
led2 = [ 682, 647, 5,]
led3 = [ 634, 655, 5,]
led4 = [ 641, 650, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-24-40.raw"
led1 = [ 677, 406, 5,]
led2 = [ 682, 400, 5,]
led3 = [ 635, 408, 5,]
led4 = [ 641, 403, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-25-00.raw"
led1 = [ 660, 408, 5,]
led2 = [ 688, 402, 5,]
led3 = [ 629, 406, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-25-18.raw"
led1 = [ 641, 410, 5,]
led2 = [ 682, 405, 5,]
led3 = [ 634, 404, 5,]
led4 = [ 675, 401, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-25-35.raw"
led1 = [ 627, 406, 5,]
led2 = [ 660, 408, 5,]
led4 = [ 686, 402, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-25-51.raw"
led1 = [ 633, 403, 5,]
led2 = [ 641, 410, 5,]
led3 = [ 674, 400, 5,]
led4 = [ 681, 405, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-26-09.raw"
led2 = [ 629, 406, 5,]
led3 = [ 688, 402, 5,]
led4 = [ 662, 409, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-26-26.raw"
led1 = [ 678, 400, 5,]
led2 = [ 636, 403, 5,]
led3 = [ 682, 405, 5,]
led4 = [ 641, 409, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-26-43.raw"
led1 = [ 689, 402, 5,]
led3 = [ 662, 408, 5,]
led4 = [ 631, 406, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-27-01.raw"
led1 = [ 683, 407, 5,]
led2 = [ 677, 400, 5,]
led3 = [ 638, 408, 5,]
led4 = [ 635, 402, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-27-19.raw"
led1 = [ 660, 407, 5,]
led2 = [ 687, 402, 5,]
led3 = [ 629, 406, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-27-40.raw"
led1 = [ 639, 411, 5,]
led2 = [ 683, 407, 5,]
led3 = [ 638, 402, 5,]
led4 = [ 679, 399, 5,]

[[recordings]]
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-27-59.raw"
led1 = [ 631, 405, 5,]
led2 = [ 661, 407, 5,]
led4 = [ 690, 401, 5,]

[[recordings]]
#here the LED3 is not visible over LED4
filepath = "/home/jakub/mrs/git/rssr_dataset/5/recording_2025-01-10_13-28-18.raw"
led1 = [ 639, 402, 5,]
led2 = [ 643, 410, 5,]
led4 = [ 683, 405, 5,]

